spring.application.name=transaction 
# Initial balance (set this to your current bank balance when you first deploy)
app.balance.initial=${INITIAL_BALANCE:0}

# Telegram config (we'll use these in the next step)
app.telegram.bot-token=${TELEGRAM_BOT_TOKEN}
app.telegram.chat-id=${TELEGRAM_CHAT_ID}

app.telegram.tracker-token=${TELEGRAM_TRACK_TOKEN}
app.telegram.tracker-id = ${TELEGRAM_TRACK_ID}

# Bank account identifier (in case you switch banks or have multiple accounts)
app.bank.account-id=X8671

# SMS patterns - if Kotak changes their format slightly, tweak here instead of code
app.sms.sent-pattern=Sent Rs\\.([\\d]+\\.\\d+) from Kotak Bank AC \\w+ to (.+?) on (\\d{2}-\\d{2}-\\d{2})\\.UPI Ref\\s*(\\d+)
app.sms.received-pattern=Received Rs\\.([\\d]+\\.\\d+) in your Kotak Bank AC \\w+ from (.+?) on (\\d{2}-\\d{2}-\\d{2})\\.UPI Ref:?(\\d+)
app.sms.deposit-pattern=INR ([\\d]+\\.\\d+) is credited to your A/c \\w+ on ([\\d-]+).*Combined Available Balance is INR ([\\d]+\\.\\d+)

# Server port
server.port=8080